required-prompt: true

stages:
  - name: plan
    type: agent
    skip_if_exists: plan
    prompt:
      - "{{prompt}}"
    interpolation:
      instructions: "artifact.instructions?"
    bind:
      artifact.plan: "file://session/plan.md"
    options:
      idle_timeout: 600

  - name: set-description
    type: exec
    bind:
      artifact.description?: "file://session/description.txt"
    options:
      cmds:
        - "head -1 \"{artifact:plan}\" | sed 's/^#\\+ *//' > \"{artifact_dir}/description.txt\""