from typing import Any

class PyConfig:
    """Python-exposed Config wrapper."""
    def __init__(self) -> None: ...
    def load(self) -> None: ...
    @property
    def default_client(self) -> str | None: ...
    def default_client_by_stage(self) -> tuple[dict[str, str], dict[str, str]]: ...
    @property
    def raw(self) -> dict[str, Any]: ...

def init() -> None: ...
def get_config() -> PyConfig: ...
def clear() -> None: ...
def state_root(config: PyConfig | None = None) -> str: ...
def work_root(config: PyConfig | None = None) -> str: ...
def user_config_root(config: PyConfig | None = None) -> str: ...
def project_root(config: PyConfig | None = None) -> str: ...
def project_overlay_dir(project_root: str, config: PyConfig | None = None) -> str: ...
def scratch_root(
    gremlin_id: str | None = None, config: PyConfig | None = None
) -> str: ...
